/* A self-contained, replayable walkthrough using a dedicated sample thread. */
(()=>{
  const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));
  const seenKey='weave-guide-seen-v1';let active=false,index=0,busy=false,session=0,source=null;
  const trigger=document.createElement('button');trigger.className='tour-trigger';trigger.id='startWeaveGuide';trigger.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m12 3 2.7 6.3L21 12l-6.3 2.7L12 21l-2.7-6.3L3 12l6.3-2.7Z"/></svg>体验引导';
  document.querySelector('.topbar-right').prepend(trigger);
  const invite=document.createElement('aside');invite.className='tour-invite';invite.innerHTML='<button class="tour-dismiss" aria-label="关闭引导邀请">×</button><div class="tour-eyebrow">A little orientation</div><h2>从一句话，走进一张想法地图。</h2><p>第一次来到 Weave？用 2 分钟，跟着引导了解每个关键按钮。</p><button class="tour-primary">开始体验 <span>↗</span></button>';document.body.append(invite);invite.hidden=!!localStorage.getItem(seenKey);
  const root=document.createElement('div');root.id='weaveTour';root.hidden=true;root.innerHTML='<div class="tour-shade"></div><div class="tour-shade"></div><div class="tour-shade"></div><div class="tour-shade"></div><div class="tour-spotlight"></div><section class="tour-card" role="dialog" aria-label="Weave 操作引导" tabindex="-1"><button class="tour-dismiss" aria-label="结束步骤引导">×</button><div class="tour-step"><span class="tour-eyebrow">Weave · Guided tour</span><span class="tour-count"></span></div><div aria-live="polite"><h2></h2><div class="tour-description"></div></div><div class="tour-footnote"></div><div class="tour-controls"><button class="tour-back">← 上一步</button><button class="tour-primary"></button></div><div class="tour-progress"></div></section><div class="tour-transition-label">正在把对话展开为结构…</div>';document.body.append(root);
  const card=root.querySelector('.tour-card'),next=root.querySelector('.tour-primary'),back=root.querySelector('.tour-back');
  function dismissInvite(){invite.hidden=true;localStorage.setItem(seenKey,'1')}
  function closeSurfaces(){['historyPopover','settingsPopover','executionSheet'].forEach(id=>$(id)?.classList.remove('show'));$('app').classList.remove('inspector-open')}
  async function chat(){closeSurfaces();WeaveFocus.dismiss();await WeaveStudio.conversation();await wait(180)}
  function sampleSource(){const t=WeaveChat.getCurrent(),m=t.messages.find(m=>m.content.includes('上下文污染（context contamination）'))||t.messages.find(m=>m.role==='assistant');const quote=m.content.includes('上下文污染（context contamination）')?'上下文污染（context contamination）':m.content.slice(0,24);return {threadId:t.id,messageId:m.id,start:m.content.indexOf(quote),end:m.content.indexOf(quote)+quote.length,quote,scrollTop:0}}
  function sourceElement(){return document.querySelector('[data-message="'+source.messageId+'"] .chat-message-text')}
  async function selectSource(){await chat();const el=sourceElement();el.scrollIntoView({block:'center',behavior:'instant'});const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n,offset=0,a,b;while(n=walker.nextNode()){let end=offset+n.length;if(!a&&source.start<end)a=[n,source.start-offset];if(source.end<=end){b=[n,source.end-offset];break}offset=end}if(a&&b){const range=document.createRange();range.setStart(...a);range.setEnd(...b);const s=getSelection();s.removeAllRanges();s.addRange(range);el.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));await wait(160)}}
  async function openBranch(){await chat();WeaveFocus.openFromMessage(source);await wait(1050)}
  function anchor(){return document.querySelector('[data-message="'+source.messageId+'"] [data-anchor]')||sourceElement()}
  async function map(){closeSurfaces();WeaveFocus.dismiss();if($('app').classList.contains('chat-mode')){root.classList.add('tour-moving');try{await WeaveStudio.reveal()}finally{root.classList.remove('tour-moving')}}await wait(180)}
  async function detail(){await map();const n=WeaveApp.getNodes().find(n=>n.explorationId)||WeaveApp.getNodes().find(n=>n.id!=='root')||WeaveApp.getRoot();WeaveApp.selectNode(n.id);await wait(180)}
  const steps=[
    {title:'先认识你的工作空间',target:()=>document.querySelector('.sidebar'),body:'<dl><dt>＋ 新对话</dt><dd>从一个新问题开始。</dd><dt>对话</dt><dd>回到聊天，继续当前思路。</dd><dt>图谱</dt><dd>看见对话里的想法与分支。</dd><dt>历史</dt><dd>找回之前的对话。</dd></dl>',note:'本次使用独立的「引导演示」对话。',cta:'看看聊天输入 →',enter:chat},
    {title:'像平常一样，先聊起来',target:()=>$('chatComposer'),body:'<dl><dt>输入框</dt><dd>提问、追问，进行长对话。</dd><dt>↑ 发送</dt><dd>发送当前问题。</dd><dt>模型选择</dt><dd>选择这段对话使用的模型。</dd><dt>···</dt><dd>设置回复来源、连接本机 CLI。</dd></dl>',note:'接下来，从示例回答中的一句话展开探索。',cta:'试试选中文字 →',enter:chat},
    {title:'遇到一个值得追问的词',target:()=>{const s=getSelection();const r=s.rangeCount?s.getRangeAt(0).getBoundingClientRect():anchor().getBoundingClientRect();const t=$('exploreTooltip').getBoundingClientRect();return {left:Math.min(r.left,t.left),top:Math.min(r.top,t.top),right:Math.max(r.right,t.right),bottom:Math.max(r.bottom,t.bottom)}},body:'<p>在回答里<b>选中一段文字</b>，就会出现「旁边问问 ↗」。</p><p>点击它，从这句话开一条侧边探索；原来的聊天位置会被保留。</p>',note:'这里已经帮你选中了「上下文污染」。',cta:'打开侧边探索 ↗',enter:selectSource},
    {title:'把岔开的念头放在旁边',target:()=>$('explorePanel'),body:'<dl><dt>顶部引文</dt><dd>记录探索从哪句话开始。</dd><dt>输入框 / ↑</dt><dd>沿着这个问题继续追问。</dd><dt>返回原文</dt><dd>回到主对话的那句话。</dd><dt>保留想法</dt><dd>把有价值的发现留进图谱。</dd></dl>',note:'细线连接原句与探索，帮你保持方向感。',cta:'试试返回原文 ↶',enter:openBranch},
    {title:'回来时，不用重新找位置',target:anchor,body:'<p>「返回原文」会把你带回<b>准确的原句</b>，并短暂高亮它。</p><p>原句上的细下划线是探索入口。以后点击这句话，就能继续同一条分支。</p>',note:'接下来，把这条探索保留下来。',cta:'重新打开并保留 →',enter:async()=>{await openBranch();$('exploreReturn').click();await wait(550)}},
    {title:'留下发现，让想法积累',target:()=>$('railMap'),body:'<p>「保留想法」会把这条探索收进图谱，左侧图谱入口会出现 <b>+1</b> 的反馈。</p><p>点击<b>图谱图标</b>或页面上的<b>「看见结构」</b>，聊天中的问题、发现和决定会逐渐展开。</p>',note:'不是重新开始：每个想法都保留对话来源。',cta:'看见结构 ↗',enter:async()=>{await openBranch();const b=WeaveChat.getCurrent().explorations.find(b=>b.quote===source.quote);if(!b?.promoted){$('explorePromote').click();await wait(850)}else WeaveFocus.dismiss()}},
    {title:'像整理思路一样整理地图',target:()=>$('graphViewport'),body:'<dl><dt>节点</dt><dd>点击查看内容与来源。</dd><dt>节点旁的折叠按钮</dt><dd>收起或展开下级分支。</dd><dt>画布 / 缩放工具</dt><dd>移动视野，放大、缩小、居中。</dd><dt>顶部视图切换</dt><dd>在对话、混合、图谱间切换。</dd></dl>',note:'下一步，打开刚才保留的想法。',cta:'点开一个想法 →',enter:map},
    {title:'每个想法，都有来处和下一步',target:()=>document.querySelector('.inspector'),body:'<dl><dt>返回原句</dt><dd>回到这个想法对应的聊天。</dd><dt>继续探索</dt><dd>沿着这个节点继续追问。</dd><dt>交给代理</dt><dd>为这个想法准备执行任务。</dd><dt>··· 更多</dt><dd>重命名、调整父节点、添加或折叠分支。</dd></dl>',note:'节点详情按需打开，让画布保持清晰。',cta:'看看代理面板 →',enter:detail},
    {title:'从一个想法，走向一次执行',target:()=>$('executionSheet'),body:'<dl><dt>任务</dt><dd>编辑 Prompt、模型与执行设置。</dd><dt>分发 / ■ 停止</dt><dd>手动开始或中止当前任务。</dd><dt>日志</dt><dd>查看执行过程与状态。</dd><dt>记录与验收</dt><dd>管理 checkpoint，回看进度与成果。</dd></dl>',note:'引导不会自动运行 CLI。完成后，可随时从右上角重新体验。',cta:'完成引导 ✓',enter:async()=>{await detail();WeaveStudio.showExecution();await wait(160)}}
  ];
  function rect(){let el=steps[index].target();if(!el)return {left:innerWidth/2,top:innerHeight/2,right:innerWidth/2+1,bottom:innerHeight/2+1};return el.getBoundingClientRect?el.getBoundingClientRect():el}
  function position(){if(!active||busy)return;const r=rect(),pad=7,x=Math.max(4,r.left-pad),y=Math.max(4,r.top-pad),right=Math.min(innerWidth-4,r.right+pad),bottom=Math.min(innerHeight-4,r.bottom+pad),w=Math.max(1,right-x),h=Math.max(1,bottom-y);const boxes=[[0,0,innerWidth,y],[0,y,x,h],[right,y,innerWidth-right,h],[0,bottom,innerWidth,innerHeight-bottom]];root.querySelectorAll('.tour-shade').forEach((s,i)=>Object.assign(s.style,{left:boxes[i][0]+'px',top:boxes[i][1]+'px',width:boxes[i][2]+'px',height:boxes[i][3]+'px'}));Object.assign(root.querySelector('.tour-spotlight').style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'});const cw=card.offsetWidth,ch=card.offsetHeight;let cx=right+22,cy=y+20;if(cx+cw>innerWidth-16)cx=x-cw-22;if(cx<16){cx=Math.max(16,(innerWidth-cw)/2);cy=y-ch-20;if(cy<16)cy=bottom+20;if(cy+ch>innerHeight-16)cy=innerHeight-ch-24}if(index===6){cx=96;cy=innerHeight-ch-28}Object.assign(card.style,{left:Math.max(12,Math.min(cx,innerWidth-cw-12))+'px',top:Math.max(12,Math.min(cy,innerHeight-ch-12))+'px'})}
  async function go(i){if(busy||!active)return;busy=true;next.disabled=true;back.disabled=true;const token=session;try{index=i;await steps[i].enter();if(!active||token!==session)return;const s=steps[i];card.querySelector('h2').textContent=s.title;card.querySelector('.tour-description').innerHTML=s.body;card.querySelector('.tour-footnote').textContent=s.note;card.querySelector('.tour-count').textContent=String(i+1).padStart(2,'0')+' / '+String(steps.length).padStart(2,'0');next.textContent=s.cta;card.querySelector('.tour-progress').innerHTML=steps.map((_,j)=>'<span class="'+(j<=i?'past':'')+'"></span>').join('')}catch(e){card.querySelector('h2').textContent='稍等一下';card.querySelector('.tour-description').textContent='请关闭引导后重新开始。你的对话仍然保留。';console.error('Weave guide:',e)}finally{busy=false;if(active&&token===session){next.disabled=false;back.disabled=index===0;position();card.focus({preventScroll:true})}}}
  async function start(){if(active||WeaveStudio.isTransitioning())return;dismissInvite();session++;active=true;root.hidden=false;closeSurfaces();WeaveFocus.dismiss();WeaveChat.openGuideSample();source=sampleSource();await go(0)}
  function finish(){session++;active=false;root.hidden=true;root.classList.remove('tour-moving');getSelection().removeAllRanges();$('exploreTooltip')?.classList.remove('show');closeSurfaces();trigger.focus({preventScroll:true})}
  trigger.onclick=start;invite.querySelector('.tour-primary').onclick=start;invite.querySelector('.tour-dismiss').onclick=dismissInvite;root.querySelector('.tour-dismiss').onclick=finish;next.onclick=()=>index===steps.length-1?finish():go(index+1);back.onclick=()=>go(Math.max(0,index-1));
  document.addEventListener('keydown',e=>{if(!active)return;if(e.key==='Escape'){e.preventDefault();finish()}if(e.key==='Tab'){const items=[...card.querySelectorAll('button:not(:disabled)')];const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===card)){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||!card.contains(document.activeElement))){e.preventDefault();first.focus()}}});
  window.addEventListener('resize',position);document.addEventListener('scroll',position,true);let frame;const observe=new ResizeObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(position)});observe.observe(document.querySelector('.main-stage'));window.WeaveTour={start,close:finish};
})();

