/* Presentation translation never rewrites user messages or source offsets. */
(()=>{
  'use strict';
  let language=localStorage.getItem('weave-language')==='en'?'en':'zh';
  const dict={
    '体验引导':'Take a tour','开始体验':'Start exploring','关闭引导邀请':'Dismiss tour invitation','从一句话，走进一张想法地图。':'Follow a thought. See where it leads.','第一次来到 Weave？用 2 分钟，跟着引导了解每个关键按钮。':'New to Weave? Take a two-minute tour of the controls and the ideas behind them.',
    '新对话':'New conversation','＋ 新对话':'+ New conversation','＋ 新分支':'+ New branch','对话':'Chat','结构':'Map','图谱':'Idea map','历史记录':'History','最近对话':'Recent conversations','关闭历史记录':'Close history','思考视图':'Thinking views','对话视图':'Conversation view','对话与结构批注':'Conversation with idea annotations','结构视图':'Map view','更多':'More','对话设置':'Conversation settings','关闭设置':'Close settings','回复来源':'Reply source','示例使用预设回答。启动本地服务后，可选择 Claude Code。':'The demo uses scripted replies. Start the local server to use Claude Code.','一个念头，从这里展开。':'Every thought opens a possibility.','跟着问题走，随时回到原处。':'Follow your curiosity. Keep your place.','打开一段示例对话 ↗':'Explore a sample conversation ↗','继续这个想法…':'Keep this thought going…','看见结构':'Reveal the map','运行代理':'Run an agent','关闭运行面板':'Close agent panel','任务':'Task','日志':'Logs','记录与验收':'Checkpoints & review','关闭想法详情':'Close idea details','打开既有图谱 ↗':'Open saved map ↗','回复来源：Claude Code':'Reply source: Claude Code','回复来源：预设示例':'Reply source: scripted demo','通过本机 Claude Code 回复':'Replies from local Claude Code','当前回答为交互演示；点击更改来源':'Scripted demo replies. Click to change the source.','示例对话使用预设回答；点击更改对话设置。':'This sample uses scripted replies. Click for conversation settings.',
    '侧边探索':'Side exploration','旁边问问 ↗':'Explore on the side ↗','收起侧边探索':'Close side exploration','来自原回答':'FROM THE ORIGINAL REPLY','继续追问…':'Ask a follow-up…','发送侧边问题':'Send side question','保留为想法':'Keep this idea','保留为想法 ↗':'Keep this idea ↗','保留想法 ↗':'Keep this idea ↗','已保留':'Kept','返回原文 ↶':'Back to the passage ↶','已回到刚才这句':'Back where you left off','值得留下的想法，会在这里相连。':'The ideas you keep find their connections here.','在对话中探索一个侧问题，回到原文，再把有价值的发现保留下来。':'Explore a side question, return to the passage, and keep the discoveries worth revisiting.','回到对话 →':'Back to the conversation →','回到原句 ↗':'Go to source ↗','继续探索 ↗':'Explore further ↗','交给代理':'Give to an agent','更多想法操作':'More idea actions','重命名':'Rename','添加分支':'Add a branch','折叠 / 展开':'Collapse / expand','上级想法':'Parent idea','想法标题':'Idea title','想法详情':'Idea details','你':'You','正在回答这个侧问题…':'Exploring this question…','这个想法来自一段对话。':'This idea grew out of a conversation.','来源对话暂不可用':'Source conversation unavailable','已保留的想法':'A kept idea','待探索的问题':'An open question','已记录的决定':'A recorded decision','来自对话 · 可继续探索':'From a conversation · ready to explore','已探索 · 点击继续':'Explored · click to continue','侧边探索 · 点击打开':'Side exploration · click to open',
    '聊天模型':'Chat model','聊天模式':'Reply mode','发送消息':'Send message','演示聊天':'Demo chat','本地 Claude Code':'Local Claude Code','本地 Claude Code（未连接）':'Local Claude Code (disconnected)','本地 Claude Code（真实）':'Local Claude Code (live)','连接本地 Claude Code':'Connect local Claude Code','本地 Claude Code 已就绪':'Local Claude Code is ready','重新检测 Claude Code':'Check for Claude Code again','长对话如何长出新想法':'Where a long conversation can lead','Weave · 引导演示':'Weave · Guided exploration','长对话，从一个问题开始':'A long conversation starts with one question','想法图谱':'Idea map','双击可重命名':'Double-click to rename','点击“新对话”，从一个问题开始。':'Start with a question in a new conversation.','一个问题，可以长出很多方向。':'One question. Many possible directions.','复制':'Copy','◇ 标记想法':'◇ Mark as an idea','✦ 已标记想法':'✦ Idea marked','正在回应':'Responding','这条回复完成后就可以开始新对话':'Start a new conversation once this reply is complete.','已创建新对话':'New conversation created','单条消息请控制在 6000 字以内':'Keep each message under 6,000 characters.','先启动本地服务，或切换为演示聊天':'Start the local server or switch to demo chat.','会话已失效；消息已保留在输入框，请重试。':'This session expired. Your message is still in the input; please try again.','浏览器本地存储已满；请复制需要保留的对话内容。':'Browser storage is full. Copy any conversations you want to keep.','本地服务没有返回 JSON':'The local server did not return JSON.','Claude Code 没有返回回复':'Claude Code did not return a reply.','Claude Code 返回了空回复':'Claude Code returned an empty reply.','侧边对话没有收到回复':'No reply was received for this exploration.',
    '主问题':'Main question','待解问题':'Open question','留下的想法':'Kept idea','决定':'Decision','想法':'Idea','旁支':'Tangent','下一步':'Next step','想法，开始显露结构':'Your ideas are taking shape','沿着来处，彼此相连':'Connected by where they began','折叠全部':'Collapse all','展开全部':'Expand all','定位':'Focus','全图':'Fit map','折叠或展开所有一级分支':'Collapse or expand all top-level branches','定位当前节点':'Focus selected node','适配全图':'Fit the whole map','缩小':'Zoom out','放大':'Zoom in','交互思维图谱':'Interactive idea map','原生长对话':'Conversation','图谱小地图':'Map navigator','已完成':'Completed','运行中':'Running','待验收':'Ready for review','待探索':'To explore','已停止':'Stopped','已取消':'Cancelled','失败':'Failed','已通过':'Approved','已验收':'Accepted','待运行':'Ready','排队中':'Queued','执行中':'Running','未启动':'Not started','未运行':'Not run','进行中':'In progress','无记录':'No records','退出码 0':'Exit code 0','演示完成':'Demo complete','需要修改':'Needs revision','待人工确认':'Awaiting your review',
    '分发 Prompt':'Task prompt','执行模型':'Model','执行权限':'Permissions','Plan · 只规划':'Plan · read only','Default · 可执行':'Default · execution enabled','执行方式':'Execution mode','演示运行':'Demo run','分发给执行代理':'Run with agent','查看当前运行':'View current run','停止当前任务':'Stop current task','状态':'Status','已用时间':'Elapsed','指挥当前节点':'Direct this idea','整理思路':'Organize ideas','＋ 添加子分支':'+ Add child branch','⊞ 展开子分支':'⊞ Expand children','⊟ 折叠子分支':'⊟ Collapse children','⊞ 折叠子分支':'⊞ Collapse children','暂无子分支':'No child branches','本地进程日志':'Local process logs','演示日志':'Demo logs','进程状态':'Process status','退出码':'Exit code','输出事件':'Output events','本地进程运行中':'Local process running','节点执行轨迹':'Idea execution history','＋ 记录 checkpoint':'+ Save checkpoint','人工验收':'Your review','任务运行':'Run status','产出记录':'Output records','验收结论':'Review decision','写下验收依据或需要修改的地方…':'Note the evidence for approval, or what needs to change…','✓ 验收通过':'✓ Approve result','↶ 需要修改':'↶ Request changes','验收由你确认；进程退出与日志仅是辅助证据。':'You decide whether to approve. Logs and exit codes provide supporting evidence.','尚无运行日志。分发任务后，输出会显示在这里。':'No logs yet. Run a task to see its output here.','尚无记录点。任务运行时可以保存证据快照。':'No checkpoints yet. Save a snapshot while a task is running.','运行证据记录点':'Execution snapshot','当前节点的执行记录为演示数据。':'Execution records for this idea are demo data.','将启动本机 Claude Code；先在 Plan 模式审阅任务。':'This starts local Claude Code. Review the task in Plan mode first.','演示运行会生成模拟进度与日志；只有选择本地模式才会调用 CLI。':'Demo runs simulate progress and logs. Only local mode invokes the CLI.','本地执行状态来自 Claude Code 进程；验收结论由你确认。':'Local status comes from the Claude Code process. You make the review decision.',
    '关闭':'Close','从这个想法，长出新分支':'Give this idea a new direction','分支标题':'Branch title','例如：如何设计任务验收？':'For example: How should we review the results?','给执行代理的初始 Prompt':'Initial prompt for the agent','这个分支想探索什么？也可以稍后再写。':'What would you like to explore? You can add this later.','取消':'Cancel','创建分支 ↗':'Create branch ↗','先给这个分支起一个名字':'Give this branch a name first.','新分支已加入图谱':'Branch added to the map','先写下要分发的 Prompt':'Write a task prompt first.','当前任务正在运行；停止后可重新分发':'This task is running. Stop it before starting another run.','请先分发任务，再记录执行快照':'Run a task before saving a checkpoint.','请等待任务结束后再验收':'Wait for the task to finish before reviewing it.','已保存运行证据快照':'Execution snapshot saved','已保存演示记录点':'Demo checkpoint saved','已记录人工验收通过':'Approval recorded','已记录需要修改':'Revision requested','已记录演示验收通过':'Demo approval recorded','已标记需要修改':'Marked for revision','演示任务已停止':'Demo task stopped','演示任务已停止。':'Demo task stopped.','已请求停止本地任务':'Stop requested for the local task','已请求取消本地进程。':'Cancellation requested for the local process.','本地 Claude Code 尚未连接':'Local Claude Code is not connected.','真实任务已提交给本机 Claude Code':'Task submitted to local Claude Code','演示任务已启动，观察水流与节点生长':'Demo started. Follow the flow through the map.','演示任务完成，等待人工验收':'Demo complete. Ready for your review.','运行结束':'Run finished','演示任务完成，等待人工验收。':'Demo complete. Ready for your review.','演示任务完成。请在记录点中查看并手动验收。':'Demo complete. Review the checkpoints and approve the result yourself.','请运行 node server.mjs，再打开 http://127.0.0.1:4173/':'Run node server.mjs, then open http://127.0.0.1:4173/',
    '稍等一下':'One moment','请关闭引导后重新开始。你的对话仍然保留。':'Close the tour and start again. Your conversations are still saved.','Weave 操作引导':'Weave guided tour','结束步骤引导':'Close guided tour','← 上一步':'← Back','正在把对话展开为结构…':'Turning the conversation into a map…'
  };
  Object.assign(dict,{
    '已复制消息':'Message copied','当前浏览器无法复制':'Copy is unavailable in this browser.','演示任务已分发。此模式不会调用外部 CLI。':'Demo task dispatched. This mode does not invoke an external CLI.','任务范围确认':'Scope confirmed','已保留节点 Prompt、模型与当前状态。':'Prompt, model, and current state captured.','正在拆解任务范围与计划步骤…':'Defining the scope and planning the steps…','产出草稿':'Draft output','已有阶段性输出；等待后续完成。':'An interim result is available. Waiting for completion.','阶段产出已形成，可进入验收前检查。':'Draft output is ready for a preliminary review.','本地桥接已连接 · 等待分发':'Local bridge connected · ready for tasks','本地桥接已连接 · 未检测到 CLI':'Local bridge connected · CLI not found','已连接本机 Claude Code，可分发真实任务':'Local Claude Code connected. Live tasks are available.','桥接已启动，但未检测到 Claude Code':'The bridge is running, but Claude Code was not found.','演示模式 · 本地桥接未连接':'Demo mode · local bridge disconnected','演示模式 · 未连接本地 CLI':'Demo mode · no local CLI connected','演示模式 · 回复为交互示例 · 对话保存在当前浏览器':'Demo mode · scripted replies · saved in this browser','Claude Code · 对话保存在当前浏览器':'Claude Code · saved in this browser','本地 Claude Code 未连接；切换至演示聊天或启动 node server.mjs。':'Local Claude Code is disconnected. Switch to demo chat or run node server.mjs.','聊天记录':'Conversation history','分支':'Branch','待处理':'Pending','未连接':'Disconnected','就绪':'Ready','当前没有运行中的任务':'No tasks are running','选中一个节点并分发 Prompt，查看执行轨迹':'Select an idea and run a prompt to follow its progress.','演示任务运行中 · 浇灌动画同步':'Demo task running · follow the flow','已完成运行 · 等待人工验收':'Run complete · awaiting your review','本地 Claude Code · 日志与退出码可查看':'Local Claude Code · logs and exit code available','选中图谱节点，查看它的上下文与执行状态。':'Select an idea to see its context and execution state.','本地 CLI':'Local CLI','演示':'Demo','重置示例 ↺':'Reset sample ↺','折叠分支':'Collapse branch','展开分支':'Expand branch'
  });
  Object.assign(dict,{'展开子分支':'Expand child branches','折叠子分支':'Collapse child branches','运行失败':'Failed','由织思面板记录的运行状态与输出片段。':'Run status and output captured from Weave.'});
  function t(value){if(language!=='en')return value;return dict[value]??value}
  function display(value){if(language!=='en')return value;const trim=value.trim();if(dict[trim])return value.replace(trim,dict[trim]);let out=value;
    const patterns=[[/^(\d+) 条消息$/,'$1 messages'],[/^(\d+) 条记录$/,'$1 records'],[/^第 (\d+) 条消息 · AI 回答/,'Message $1 · AI reply'],[/^第 (\d+) 条消息 · 你的提问/,'Message $1 · Your question'],[/^来源节点：/,'Parent idea: '],[/^继续探索：/,'Continue exploring: '],[/^模拟/,'Demo · '],[/^发送失败：/,'Could not send: '],[/^分发失败：/,'Could not start: '],[/^保存失败：/,'Could not save: '],[/^停止失败：/,'Could not stop: '],[/^验收记录失败：/,'Could not record review: '],[/^未连接本地桥接：/,'Local bridge disconnected: '],[/^本地状态读取失败：/,'Could not read local status: ']];
    for(const [re,replacement]of patterns)out=out.replace(re,replacement);
    if(out.startsWith('Demo · '))out='Demo · '+t(out.slice(7));
    out=out.replace(/^展开 (\d+) 个子分支$/,'Expand $1 child branches').replace(/^折叠 (\d+) 个子分支$/,'Collapse $1 child branches').replace(/^记录点 (\d+)$/,'Checkpoint $1').replace(/^演示状态 (.+)；进度 ([\d.]+)%。$/,(_,status,progress)=>'Demo status: '+t(status)+'. Progress: '+progress+'%.');
    return out;
  }
  const records=new WeakMap(),attrs=new WeakMap();
  // These regions contain user-authored text, node labels or exact source quotations.
  const content='.chat-message-text,.thread-name,#chatTopicTitle,#exploreQuote,#exploreContext,.explore-message p,#focusIdeaTitle,#focusIdeaSummary,#ideaParent,.graph-node,.shape-clone,.structure-note,#nodePath,#inspectorTitle,#inspectorSummary,#stripTitle,#candidateList,textarea,input,[data-no-i18n]';
  function translateNode(node){if(!node.parentElement||node.parentElement.closest('script,style,'+content))return;let r=records.get(node);if(!r||node.nodeValue!==r.output)r={source:node.nodeValue};const out=display(r.source);if(node.nodeValue!==out)node.nodeValue=out;r.output=out;records.set(node,r)}
  function scan(el=document.body){if(!el)return;if(el.nodeType===3){translateNode(el);return}const walk=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n;while(n=walk.nextNode())translateNode(n);for(const item of [el,...el.querySelectorAll('[title],[aria-label],[placeholder],[data-tip]')]){if(!item.getAttribute)continue;let rec=attrs.get(item)||{};for(const key of ['title','aria-label','placeholder','data-tip']){const value=item.getAttribute(key);if(value===null)continue;let r=rec[key];if(!r||r.output!==value)r={source:value};const out=display(r.source);if(value!==out)item.setAttribute(key,out);r.output=out;rec[key]=r}attrs.set(item,rec)}}
  let observer;function refresh(){observer?.disconnect();scan();observer?.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['title','aria-label','placeholder','data-tip']});document.documentElement.lang=language==='en'?'en':'zh-CN';document.title=language==='en'?'Weave — Follow your curiosity':'Weave — 让想法自由展开';const b=document.getElementById('languageSwitch');if(b)b.textContent=language==='en'?'EN / 中':'中 / EN'}
  function set(lang){const changed=language!==lang;language=lang==='en'?'en':'zh';localStorage.setItem('weave-language',language);refresh();if(changed)document.dispatchEvent(new CustomEvent('weave:language-changed',{detail:{language}}))}
  let modal,callback,previousFocus;
  function choose(done){callback=done;previousFocus=document.activeElement;modal.hidden=false;modal.querySelectorAll('[data-language]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.language===language)));modal.querySelector('[data-language="'+language+'"]').focus()}
  function dismiss(){modal.hidden=true;callback=null;previousFocus?.focus()}
  document.addEventListener('DOMContentLoaded',()=>{
    const button=document.createElement('button');button.type='button';button.className='language-switch';button.id='languageSwitch';button.setAttribute('aria-label','Language / 语言');button.onclick=()=>choose(()=>{const thread=window.WeaveChat?.getCurrent();if(thread?.guideDemo)WeaveChat.openGuideSample();else if(thread?.demo)WeaveChat.openSample()});document.querySelector('.topbar-right').prepend(button);
    modal=document.createElement('div');modal.className='language-modal';modal.hidden=true;modal.dataset.noI18n='';modal.innerHTML='<section role="dialog" aria-modal="true" aria-labelledby="languageTitle"><button class="language-close" aria-label="Close / 关闭">×</button><div class="tour-eyebrow">WEAVE · MAKE YOURSELF AT HOME</div><div class="language-symbol">文<span> A</span></div><h2 id="languageTitle">选择你的语言</h2><p>Choose the language for your experience.</p><div class="language-options"><button data-language="zh"><strong>中文</strong><small>简体中文</small><span>✓</span></button><button data-language="en"><strong>English</strong><small>English</small><span>✓</span></button></div><button class="language-continue tour-primary">继续 / Continue →</button><small class="language-note">随时可以切换 · You can switch anytime</small></section>';document.body.append(modal);modal.querySelectorAll('[data-language]').forEach(b=>b.onclick=()=>{set(b.dataset.language);modal.querySelectorAll('[data-language]').forEach(c=>c.setAttribute('aria-pressed',String(c===b)))});modal.querySelector('.language-close').onclick=dismiss;modal.querySelector('.language-continue').onclick=()=>{const fn=callback;modal.hidden=true;callback=null;fn?.()};modal.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();dismiss()}if(e.key==='Tab'){const buttons=[...modal.querySelectorAll('button')],first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});observer=new MutationObserver(mutations=>{observer.disconnect();for(const m of mutations){if(m.type==='characterData')scan(m.target);else if(m.type==='attributes')scan(m.target);else for(const node of m.addedNodes)if(node.nodeType===1||node.nodeType===3)scan(node)}observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['title','aria-label','placeholder','data-tip']})});refresh();
  });
  const sample=[
    ['user','I want to design a product for heavy AI users: a way to explore side questions during long conversations while keeping the main thread in view.'],
    ['assistant','Imagine spending half an hour shaping a product with AI. You start by defining the user, compare three interaction approaches, then explore the business model. By the fortieth exchange, that promising early idea is still in the conversation, but finding it takes work.\n\nThen you come across “context contamination” in an answer and want to understand it. Asking in the main conversation pulls you away from the product discussion. Opening another chat loses the connection to the passage that prompted your question.\n\nLet the exploration begin right at that phrase. Select it, ask a few questions on the side, then return to exactly where you were reading. Keep the discoveries you want to revisit. Over time, those ideas become a map.'],
    ['user','Why do important ideas get lost in a linear chat?'],['assistant','Each new question pushes earlier ideas farther up the page. Finding one means scrolling back through everything that came after it.'],
    ['user','What if I have a small question halfway through reading? How can I explore it without losing my place?'],['assistant','Start a side exploration from the exact words you are reading. Follow the question for a few exchanges, then return to the highlighted passage. The main conversation keeps its flow.'],
    ['user','Then should every side question become part of the map?'],['assistant','Only if you choose to keep it. Some questions simply help you understand a passage. Others lead to discoveries you want to develop or revisit. Keep those as ideas.'],
    ['user','Back to the main thread: the first version should focus on selecting a passage, exploring, returning to it, and keeping an idea.'],['assistant','Make that journey the heart of the demo. The map grows from the ideas you keep, and every node can take you back to its source.']
  ];
  window.WeaveI18n={get language(){return language},t,set,refresh,choose,register:entries=>Object.assign(dict,entries),sampleMessages:()=>sample.map(([role,content],i)=>({id:'s'+(i+1),role,content})),demoReply:q=>/task|agent|cli|checkpoint|review/i.test(q)?'Turn this into a task branch. Define the goal and prompt, follow the run and its checkpoints, then review the result before approving it.':/branch|side|tangent/i.test(q)?'Keep a link to the passage that sparked this question. Explore it on the side, then keep the discovery if it is worth revisiting. Reveal the map when you want to see how it connects.':'Let’s explore “'+q.slice(0,65)+'”. First clarify the goal, then consider two possible directions and the questions still open. Keep asking here, and reveal the map when you want to organize the conversation.',branchAnswer:(quote)=>/context contamination/i.test(quote)?'Context contamination happens when assumptions from one question carry into another where they no longer apply. For example, after discussing a legal contract, you ask about writing style, but the model still treats contract terms as the goal.\n\nA side exploration gives the follow-up its own thread. Once the idea is clear, you can return to the original passage and keep reading.':'Explore “'+quote+'” through a definition, an example, and a counterexample. Use this side thread to clarify the idea, then return to the exact passage when you are ready. Keep the discovery if you want to develop it later.'};
})();
