/* A self-contained, replayable walkthrough using a dedicated sample thread. */
(()=>{
  const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));
  let active=false,index=0,busy=false,session=0,source=null;
  const trigger=document.createElement('button');trigger.className='tour-trigger';trigger.id='startWeaveGuide';trigger.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m12 3 2.7 6.3L21 12l-6.3 2.7L12 21l-2.7-6.3L3 12l6.3-2.7Z"/></svg>体验引导';
  document.querySelector('.topbar-right').prepend(trigger);
  const root=document.createElement('div');root.id='weaveTour';root.hidden=true;root.innerHTML='<div class="tour-shade"></div><div class="tour-shade"></div><div class="tour-shade"></div><div class="tour-shade"></div><div class="tour-spotlight"></div><section class="tour-card" role="dialog" aria-label="Weave 操作引导" tabindex="-1"><button class="tour-dismiss" aria-label="结束步骤引导">×</button><div class="tour-step"><span class="tour-eyebrow">Weave · Guided tour</span><span class="tour-count"></span></div><div aria-live="polite"><h2></h2><div class="tour-description"></div></div><div class="tour-footnote"></div><div class="tour-controls"><button class="tour-back">← 上一步</button><button class="tour-primary"></button></div><div class="tour-progress"></div></section><div class="tour-transition-label">正在把对话展开为结构…</div>';document.body.append(root);
  const card=root.querySelector('.tour-card'),next=root.querySelector('.tour-primary'),back=root.querySelector('.tour-back');
  function closeSurfaces(){['historyPopover','settingsPopover','executionSheet','dispatchSheet','exportPopover'].forEach(id=>$(id)?.classList.remove('show'));$('app').classList.remove('inspector-open')}
  async function chat(){closeSurfaces();WeaveFocus.dismiss();await WeaveStudio.conversation();await wait(180)}
  function sampleSource(){if(WeaveI18n.language==='en'){const t=WeaveChat.getCurrent(),m=t.messages.find(m=>m.content.includes('context contamination')),quote='context contamination',start=m.content.indexOf(quote);return {threadId:t.id,messageId:m.id,start,end:start+quote.length,quote,scrollTop:0}}const t=WeaveChat.getCurrent(),m=t.messages.find(m=>m.content.includes('上下文污染（context contamination）'))||t.messages.find(m=>m.role==='assistant');const quote=m.content.includes('上下文污染（context contamination）')?'上下文污染（context contamination）':m.content.slice(0,24);return {threadId:t.id,messageId:m.id,start:m.content.indexOf(quote),end:m.content.indexOf(quote)+quote.length,quote,scrollTop:0}}
  function sourceElement(){return document.querySelector('[data-message="'+source.messageId+'"] .chat-message-text')}
  async function selectSource(){await chat();const el=sourceElement();el.scrollIntoView({block:'center',behavior:'instant'});const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n,offset=0,a,b;while(n=walker.nextNode()){let end=offset+n.length;if(!a&&source.start<end)a=[n,source.start-offset];if(source.end<=end){b=[n,source.end-offset];break}offset=end}if(a&&b){const range=document.createRange();range.setStart(...a);range.setEnd(...b);const s=getSelection();s.removeAllRanges();s.addRange(range);el.dispatchEvent(new MouseEvent('mouseup',{bubbles:true}));await wait(160)}}
  async function openBranch(){await chat();WeaveFocus.openFromMessage(source);await wait(1050)}
  /* 引导用：在 A 的回答里选中文字开子探索 B；再演示返回上一层 */
  async function openChild(){
    await openBranch();
    const branch=WeaveChat.getCurrent().explorations.find(b=>b.quote===source.quote);
    if(!branch)return;
    const text=WeaveI18n.language==='en'?'no longer apply':'不该继承的假设';
    for(let i=0;i<6&&!WeaveFocus.openChildFromBranch(branch.id,text);i+=1)await wait(350);
    await wait(700);
  }
  async function backUp(){
    if(!$('app').classList.contains('explore-open'))await openChild();
    for(let i=0;i<10&&$('exploreReturn').disabled;i+=1)await wait(400);
    window.WeaveFocus?.returnUp?.();
    await wait(500);
  }
  function anchor(){return document.querySelector('[data-message="'+source.messageId+'"] [data-anchor]')||sourceElement()}
  async function map(){closeSurfaces();WeaveFocus.dismiss();if($('app').classList.contains('chat-mode')){root.classList.add('tour-moving');try{await WeaveStudio.reveal()}finally{root.classList.remove('tour-moving')}}await wait(180)}
  async function detail(){await map();const n=WeaveApp.getNodes().find(n=>n.explorationId)||WeaveApp.getNodes().find(n=>n.id!=='root')||WeaveApp.getRoot();WeaveApp.selectNode(n.id);await wait(180)}
  const steps=[
    {title:'先认识你的工作空间',target:()=>document.querySelector('.sidebar'),body:'<dl><dt>＋ 新对话</dt><dd>从一个新问题开始。</dd><dt>对话 / 图谱</dt><dd>在聊天与结构之间切换。</dd><dt>任务分发</dt><dd>为节点分配模型并批量执行。</dd><dt>导出文档</dt><dd>把图谱导出为 Word 或幻灯片。</dd><dt>历史</dt><dd>找回之前的对话。</dd></dl>',note:'本次使用独立的「引导演示」对话。',cta:'看看聊天输入 →',enter:chat},
    {title:'像平常一样，先聊起来',target:()=>$('chatComposer'),body:'<dl><dt>输入框</dt><dd>提问、追问，进行长对话。</dd><dt>↑ 发送</dt><dd>发送当前问题。</dd><dt>模型选择</dt><dd>选择这段对话使用的模型。</dd><dt>···</dt><dd>设置回复来源、连接本机 CLI。</dd></dl>',note:'接下来，从示例回答中的一句话展开探索。真实 Claude 会话接近上限时会自动整理较早上下文；完整记录仍保留。',cta:'试试选中文字 →',enter:chat},
    {title:'遇到一个值得追问的词',target:()=>{const s=getSelection();const r=s.rangeCount?s.getRangeAt(0).getBoundingClientRect():anchor().getBoundingClientRect();const t=$('exploreTooltip').getBoundingClientRect();return {left:Math.min(r.left,t.left),top:Math.min(r.top,t.top),right:Math.max(r.right,t.right),bottom:Math.max(r.bottom,t.bottom)}},body:'<p>在回答里<b>选中一段文字</b>，就会出现「旁边问问 ↗」。</p><p>点击它，从这句话开一条侧边探索；原来的聊天位置会被保留。</p>',note:'这里已经帮你选中了「上下文污染」。',cta:'打开侧边探索 ↗',enter:selectSource},
    {title:'把岔开的念头放在旁边',target:()=>$('explorePanel'),body:'<dl><dt>顶部引文</dt><dd>记录探索从哪句话开始。</dd><dt>输入框 / ↑</dt><dd>沿着这个问题继续追问。</dd><dt>返回原文</dt><dd>回到主对话的那句话。</dd><dt>保留想法</dt><dd>把有价值的发现留进图谱。</dd></dl>',note:'细线连接原句与探索，帮你保持方向感。',cta:'在探索的回答里选中 →',enter:openBranch},
    {title:'探索里，还能再往下问',target:()=>$('explorePanel'),body:'<p>在<b>探索的回答</b>里选中一段文字，同样可以「旁边问问 ↗」。</p><p>上一层会移到中间，新的探索在右侧打开；顶部的<b>路径</b>显示当前层级，细线始终连着来源原句。</p>',note:'每层探索都是独立会话，只带走当时需要的背景。',cta:'试试回到上一层 →',enter:openChild},
    {title:'回到上一层，位置还在',target:()=>$('explorePath'),body:'<p>「返回上一层」回到刚才的探索：<b>阅读位置和输入草稿都会保留</b>。</p><p>更早的层级收进顶部路径；关闭面板只是收起，探索记录还在。</p>',note:'子探索的内容不会合并进父对话。',cta:'回到主对话 ↶',enter:backUp},
    {title:'回来时，不用重新找位置',target:anchor,body:'<p>「返回原文」会把你带回<b>准确的原句</b>，并短暂高亮它。</p><p>原句上的细下划线是探索入口。以后点击这句话，就能继续同一条分支。</p>',note:'接下来，把这条探索保留下来。',cta:'重新打开并保留 →',enter:async()=>{await openBranch();$('exploreReturn').click();await wait(550)}},
    {title:'留下发现，让想法积累',target:()=>$('railMap'),body:'<p>「保留想法」会把这条探索收进图谱，左侧图谱入口会出现 <b>+1</b> 的反馈。</p><p>点击<b>图谱图标</b>或页面上的<b>「看见结构」</b>，聊天中的问题、发现和决定会逐渐展开。</p>',note:'不是重新开始：每个想法都保留对话来源。',cta:'看见结构 ↗',enter:async()=>{await openBranch();const b=WeaveChat.getCurrent().explorations.find(b=>b.quote===source.quote);if(!b?.promoted){$('explorePromote').click();await wait(850)}else WeaveFocus.dismiss()}},
    {title:'像整理思路一样整理地图',target:()=>$('graphViewport'),body:'<dl><dt>节点</dt><dd>点击查看内容与来源。</dd><dt>拖动节点</dt><dd>拖到节点中央变为子想法；拖到上下边缘并列插入。聊天顺序随结构重排。</dd><dt>节点旁的折叠按钮</dt><dd>收起或展开下级分支。</dd><dt>画布 / 缩放工具</dt><dd>移动视野，放大、缩小、居中。</dd><dt>顶部视图切换</dt><dd>在对话、混合、图谱间切换。</dd></dl>',note:'下一步，打开刚才保留的想法。',cta:'点开一个想法 →',enter:map},
    {title:'每个想法，都有来处和下一步',target:()=>document.querySelector('.inspector'),body:'<dl><dt>返回原句</dt><dd>回到这个想法对应的聊天。</dd><dt>继续探索</dt><dd>沿着这个节点继续追问。</dd><dt>交给代理</dt><dd>为这个想法准备执行任务。</dd><dt>··· 更多</dt><dd>重命名、调整父节点、添加、折叠或删除分支。</dd></dl>',note:'节点详情按需打开，让画布保持清晰。',cta:'看看代理面板 →',enter:detail},
    {title:'从一个想法，走向一次执行',target:()=>$('executionSheet'),body:'<dl><dt>任务</dt><dd>编辑 Prompt、模型与执行设置。</dd><dt>分发 / ■ 停止</dt><dd>手动开始或中止当前任务。</dd><dt>日志</dt><dd>查看执行过程与状态。</dd><dt>记录与验收</dt><dd>管理 checkpoint，回看进度与成果。</dd></dl>',note:'引导不会自动运行 CLI。完成后，可随时从右上角重新体验。',cta:'完成引导 ✓',enter:async()=>{await detail();WeaveStudio.showExecution();await wait(160)}}
  ];

  const englishSteps=[
    {title:'A place for your thinking',body:'<dl><dt>＋ New conversation</dt><dd>Start with a fresh question.</dd><dt>Chat / Idea map</dt><dd>Move between the conversation and its structure.</dd><dt>Task dispatch</dt><dd>Assign models to nodes and run them in a queue.</dd><dt>Export docs</dt><dd>Turn the map into a Word file or slides.</dd><dt>History</dt><dd>Revisit earlier conversations.</dd></dl>',note:'This tour uses its own sample conversation.',cta:'Meet the chat composer →'},
    {title:'Start with a conversation',body:'<dl><dt>Message box</dt><dd>Ask, follow up, and think out loud.</dd><dt>↑ Send</dt><dd>Send your question.</dd><dt>Model selector</dt><dd>Choose the model for this chat.</dd><dt>··· Settings</dt><dd>Choose demo replies or connect a local CLI.</dd></dl>',note:'Next, follow a thought inside a sample answer. Live Claude sessions compact earlier context automatically; the full history stays readable.',cta:'Try selecting a phrase →'},
    {title:'A phrase sparks a question',body:'<p><b>Select a phrase</b> in an answer to reveal “Explore on the side ↗”.</p><p>Open an exploration right from those words. Your place in the main conversation stays intact.</p>',note:'We have selected “context contamination” for you.',cta:'Open a side exploration ↗'},
    {title:'Give the tangent some room',body:'<dl><dt>Quoted passage</dt><dd>See where this question began.</dd><dt>Message box / ↑</dt><dd>Continue exploring this thread.</dd><dt>Back to the passage</dt><dd>Return to the original words.</dd><dt>Keep this idea</dt><dd>Save a discovery to your map.</dd></dl>',note:'A fine line keeps the exploration connected to its source.',cta:'Select inside the reply →'},
    {title:'Go one level deeper',body:'<p><b>Select a phrase inside an exploration reply</b> and “Explore on the side ↗” appears again.</p><p>The parent level moves to the middle; the new exploration opens on the right. The path at the top shows where you are, and the line keeps pointing at the source phrase.</p>',note:'Every level is its own session, carrying only the background it needs.',cta:'Try going back up →'},
    {title:'Back up a level, right where you were',body:'<p>“Up one level” returns to the previous exploration with <b>your reading position and input draft preserved</b>.</p><p>Earlier levels fold into the path; closing the panel only tidies the view — the explorations stay.</p>',note:'Nothing from a child exploration is merged into its parent.',cta:'Back to the main conversation ↶'},
    {title:'Pick up where you left off',body:'<p>“Back to the passage” returns to <b>the exact words</b> and briefly highlights them.</p><p>The underline is a doorway back into this exploration. Click it whenever you want to continue.</p>',note:'Next, keep the discovery from this side thread.',cta:'Reopen and keep the idea →'},
    {title:'Keep what is worth revisiting',body:'<p>“Keep this idea” adds the discovery to your map. A small <b>+1</b> marks the moment at the map icon.</p><p>Click the <b>map icon</b> or <b>“Reveal the map”</b> to see questions, discoveries, and decisions take shape.</p>',note:'Each idea keeps its link to the original conversation.',cta:'Reveal the map ↗'},
    {title:'Make room for connections',body:'<dl><dt>Idea nodes</dt><dd>Open the content and its source.</dd><dt>Drag a node</dt><dd>Drop on a node’s center to nest it; drop near its top or bottom edge to place it alongside. The chat follows the new order.</dd><dt>Branch toggle</dt><dd>Collapse or expand child ideas.</dd><dt>Canvas / zoom tools</dt><dd>Pan, zoom, focus, or fit the map.</dd><dt>View switch</dt><dd>Move between chat, annotations, and map.</dd></dl>',note:'Next, open the idea you just kept.',cta:'Open an idea →'},
    {title:'Every idea has a next step',body:'<dl><dt>Go to source</dt><dd>Return to the original conversation.</dd><dt>Explore further</dt><dd>Ask a question from this idea.</dd><dt>Give to an agent</dt><dd>Prepare a task for execution.</dd><dt>··· More actions</dt><dd>Rename, reparent, add, fold, or delete branches.</dd></dl>',note:'Details open when you need them, keeping the map clear.',cta:'Meet the agent panel →'},
    {title:'Turn a thought into action',body:'<dl><dt>Task</dt><dd>Edit the prompt, model, and permissions.</dd><dt>Run / ■ Stop</dt><dd>Start or stop execution yourself.</dd><dt>Logs</dt><dd>Follow the output and run status.</dd><dt>Checkpoints & review</dt><dd>Save progress and review the result.</dd></dl>',note:'The tour never starts a CLI task. Replay it anytime from the top bar.',cta:'Finish the tour ✓'}
  ];
  function rect(){let el=steps[index].target();if(!el)return {left:innerWidth/2,top:innerHeight/2,right:innerWidth/2+1,bottom:innerHeight/2+1};return el.getBoundingClientRect?el.getBoundingClientRect():el}
  function position(){if(!active||busy)return;const r=rect(),pad=7,x=Math.max(4,r.left-pad),y=Math.max(4,r.top-pad),right=Math.min(innerWidth-4,r.right+pad),bottom=Math.min(innerHeight-4,r.bottom+pad),w=Math.max(1,right-x),h=Math.max(1,bottom-y);const boxes=[[0,0,innerWidth,y],[0,y,x,h],[right,y,innerWidth-right,h],[0,bottom,innerWidth,innerHeight-bottom]];root.querySelectorAll('.tour-shade').forEach((s,i)=>Object.assign(s.style,{left:boxes[i][0]+'px',top:boxes[i][1]+'px',width:boxes[i][2]+'px',height:boxes[i][3]+'px'}));Object.assign(root.querySelector('.tour-spotlight').style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'});const cw=card.offsetWidth,ch=card.offsetHeight;let cx=right+22,cy=y+20;if(cx+cw>innerWidth-16)cx=x-cw-22;if(cx<16){cx=Math.max(16,(innerWidth-cw)/2);cy=y-ch-20;if(cy<16)cy=bottom+20;if(cy+ch>innerHeight-16)cy=innerHeight-ch-24}if(index===8){cx=96;cy=innerHeight-ch-28}Object.assign(card.style,{left:Math.max(12,Math.min(cx,innerWidth-cw-12))+'px',top:Math.max(12,Math.min(cy,innerHeight-ch-12))+'px'})}
  async function go(i){if(busy||!active)return;busy=true;next.disabled=true;back.disabled=true;const token=session;try{index=i;await steps[i].enter();if(!active||token!==session)return;const s=WeaveI18n.language==='en'?englishSteps[i]:steps[i];card.querySelector('h2').textContent=s.title;card.querySelector('.tour-description').innerHTML=s.body;card.querySelector('.tour-footnote').textContent=s.note;card.querySelector('.tour-count').textContent=String(i+1).padStart(2,'0')+' / '+String(steps.length).padStart(2,'0');next.textContent=s.cta;card.querySelector('.tour-progress').innerHTML=steps.map((_,j)=>'<span class="'+(j<=i?'past':'')+'"></span>').join('')}catch(e){card.querySelector('h2').textContent='稍等一下';card.querySelector('.tour-description').textContent='请关闭引导后重新开始。你的对话仍然保留。';console.error('Weave guide:',e)}finally{busy=false;if(active&&token===session){next.disabled=false;back.disabled=index===0;position();card.focus({preventScroll:true})}}}
  async function begin(){if(active||WeaveStudio.isTransitioning())return;session++;active=true;root.hidden=false;closeSurfaces();WeaveFocus.dismiss();WeaveChat.openGuideSample();source=sampleSource();await go(0)}
  function finish(){session++;active=false;root.hidden=true;root.classList.remove('tour-moving');getSelection().removeAllRanges();$('exploreTooltip')?.classList.remove('show');closeSurfaces();trigger.focus({preventScroll:true})}
  function start(){if(!active&&!WeaveStudio.isTransitioning())WeaveI18n.choose(begin)}
  trigger.onclick=start;root.querySelector('.tour-dismiss').onclick=finish;next.onclick=()=>index===steps.length-1?finish():go(index+1);back.onclick=()=>go(Math.max(0,index-1));
  document.addEventListener('keydown',e=>{if(!active)return;if(e.key==='Escape'){e.preventDefault();finish()}if(e.key==='Tab'){const items=[...card.querySelectorAll('button:not(:disabled)')];const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===card)){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||!card.contains(document.activeElement))){e.preventDefault();first.focus()}}});
  window.addEventListener('resize',position);document.addEventListener('scroll',position,true);let frame;const observe=new ResizeObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(position)});observe.observe(document.querySelector('.main-stage'));const langButton=document.createElement('button');langButton.className='tour-language';langButton.textContent='中 / EN';langButton.setAttribute('aria-label','Switch language / 切换语言');card.querySelector('.tour-step').append(langButton);langButton.onclick=()=>{if(busy)return;finish();start()};
  /* 打开页面即进入引导：语言弹窗的 DOM 在 DOMContentLoaded 才建立，故等窗口加载后再留一小段时间让首屏稳定。 */
  function autoStart(){if(active)return;if(WeaveStudio.isTransitioning()){setTimeout(autoStart,250);return}start()}
  function scheduleAutoStart(){setTimeout(autoStart,350)}
  if(document.readyState==='complete')scheduleAutoStart();else window.addEventListener('load',scheduleAutoStart);
  window.WeaveTour={start,close:finish};
})();

